### ISSUE TITLE
Notice: Undefined index: lazy in Drupal\term_reference_fancytree\Element\TermReferenceFancytree::getVocabularyNamesJsonArray()

### ISSUE THREAD

**Issue by manxon** [duartegarin/term_reference_fancytree#10]
Good day,

Thank you for the module, I have an error when having multiple vocabularies to select from in the tree:

Notice: Undefined index: lazy in Drupal\term_reference_fancytree\Element\TermReferenceFancytree::getVocabularyNamesJsonArray()

Checking the code it seems that the variable $item['lazy'] is not initialized

I set it  to false and the error dissapears:

`  // Load child terms for the vocabulary.
        $terms = TermReferenceFancytree::loadTerms($vocabulary, 0);
        $item['lazy'] = FALSE;
        // For each term, check if it's an ancestor of a selected item.
        // If it is, then we need to load the vocabulary folder.
        foreach ($terms as $term) {
          if (isset($ancestors[$term->id()])) {
            $item['lazy'] = FALSE;
            break;
          }
          // Otherwise, we mark it as lazy.
          else {
            $item['lazy'] = TRUE;
          }
        }

        // If the vocabulary folder is loaded, we add the active trail and
        // load its children.
        if (!$item['lazy']) {`

Regards

Julian Mancera

**Comment by manxon** [comment]
Here is the patch
[term_reference_fancytree-10-issue-663148562.log](https://github.com/duartegarin/term_reference_fancytree/files/4954897/term_reference_fancytree-10-issue-663148562.log)

**Comment by carolpettirossi** [comment]
Hi @manxon, 

Thanks for reporting this bug. I've just pushed your suggestion.

Cheers,
Carol
