### ISSUE TITLE
Translated terms are not used if they exist given current language context

### ISSUE THREAD

**Issue by jaydub2099** [duartegarin/term_reference_fancytree#14]
I have a term reference field with terms that have (spanish) translations in the taxonomy. If I use a core form widget for the term reference e.g. checkboxes, the translated terms show up on the node form when I am in spanish language context e.g. /es/node/add/node_type_name. If I switch to using the fancytree widget, the translated terms do not render, rather I get the primarly language english terms.

I have a patch in PR to fix this.

**Comment by jaydub2099** [comment]
PR added:

https://github.com/duartegarin/term_reference_fancytree/pull/15

**Comment by carolpettirossi** [comment]
Hi @jaydub2099,

Thanks for reporting the issue and providing the patch. I've tested and it works perfectly. Pushed to 1.x and 2.x branches. 

Cheers,
Carol
