### ISSUE TITLE
Error on use Term Reference Fancytree with more than one children in vocabulary taxonomies

### ISSUE THREAD

**Issue by erickmajor** [duartegarin/term_reference_fancytree#19]
When we use the Term Reference widget with vocabularies with more than one children, Drupal trigger an error related to JSON response. E.g. ```Load error! (Syntax Error: Unexpected token N in JSON at position 1)```.

This error is caused because the construct method doesn't consider the $entity_type_manager attribution in this situation:
```
  /**
   * Constructs a SubTreeController object.
   *
   * @param \Symfony\Component\HttpFoundation\Request $request
   *   The current request.
   */
  public function __construct(Request $request) {
    $this->request = $request;
    $this->entityTypeManager = $entity_type_manager;
  }
```

Could you fix this problem please?

**Comment by duartegarin** [comment]
@erickmajor can you give me steps to replicate?
I have vocabularies with several levels and seems to work fine.

**Comment by duartegarin** [comment]
I've just merged your fix.
