### ISSUE TITLE
Feature Request - Add "Select parents automatically" config

### ISSUE THREAD

**Issue by carolpettirossi** [duartegarin/term_reference_fancytree#2]
It would be good if we can configure the widget to select parents automatically if a child term is selected.

**Comment by manojbisht891** [comment]
+1

**Comment by manojbisht891** [comment]
I have added a settings in form display for selecting parent items, whose value is false initially, when user set its value to 1, then on node add/edit form, only leaves can be selected, and if leaves are selected then parent terms is selected automatically.

**Comment by manojbisht891** [comment]
https://github.com/duartegarin/term_reference_fancytree/pull/6

**Comment by chikeh** [comment]
+1 for this feature @manojbisht891 I can't find any settings in form display as you said.

**Comment by chikeh** [comment]
Okay @manojbisht891 I now see your reference, can this be used like a patch or how can it be used? Thanks.

**Comment by manojbisht891** [comment]
It can be added as patch in composer.json

**Comment by chikeh** [comment]
@manojbisht891 I have, before now, only applied patches from d.o, so in this case what will be the patch url to fix in Composer patches?

Thank you.

**Comment by manojbisht891** [comment]
https://patch-diff.githubusercontent.com/raw/duartegarin/term_reference_fancytree/pull/6.patch

**Comment by chikeh** [comment]
I learnt this after I asked and had already applied the patch, the patch works well, thank you.

**Comment by duartegarin** [comment]
Closing this as I've added the option to the latest release.
