### ISSUE TITLE
Adding a configuration option to set the selection mode.

### ISSUE THREAD

**Issue by mrbaileys** [duartegarin/term_reference_fancytree#4]
See PR [#3]

![Schermafbeelding 2019-10-07 om 11 12 51](https://user-images.githubusercontent.com/886283/66299252-6e7ea000-e8f3-11e9-99b0-a6abfb29fe7c.png)

**Comment by sashken** [comment]
It would be great!

**Comment by duartegarin** [comment]
Done in latest release.
