### ISSUE TITLE
Notice: Undefined index: target_id

### ISSUE THREAD

**Issue by ghost** [duartegarin/term_reference_fancytree#7]
There is notice when you go to the field instance configuration and you don't have a default value.

> Please enable the drupal.org issue queue.

here is the patch code:
```
diff --git a/src/Element/TermReferenceFancytree.php b/src/Element/TermReferenceFancytree.php
index 440efb5..50624ea 100644
--- a/src/Element/TermReferenceFancytree.php
+++ b/src/Element/TermReferenceFancytree.php
@@ -82,18 +82,19 @@ class TermReferenceFancytree extends FormElement {
     $all_ancestors = [];
 
     foreach ($values as $value) {
+      if (isset($value['target_id'])) {
+        // Check if we are processing input or not because the structure of
+        // default values and form state differs.
+        if(!$processing_input){
+          $value = $value['target_id'];
+        }
 
-      // Check if we are processing input or not because the structure of
-      // default values and form state differs.
-      if(!$processing_input){
-        $value = $value['target_id'];
-      }
-
-      $term_ancestors = \Drupal::entityTypeManager()
-        ->getStorage('taxonomy_term')
-        ->loadAllParents($value);
-      foreach ($term_ancestors as $ancestor) {
-        $all_ancestors[$ancestor->id()] = $ancestor;
+        $term_ancestors = \Drupal::entityTypeManager()
+          ->getStorage('taxonomy_term')
+          ->loadAllParents($value);
+        foreach ($term_ancestors as $ancestor) {
+          $all_ancestors[$ancestor->id()] = $ancestor;
+        }
       }
     }
```

**Comment by jayelless** [comment]
Please start using the drupal.org issue queue as it is the correct way for drupal projects to be managed.  How can I get a patch file for composer direct from github?  The drupal.org issue queue provides this support automatically.  PLEASE USE IT!

**Comment by duartegarin** [comment]
@jayelless I am sorry, but there are dozens of drupal of projects being used on github. Some of them quite large like graphql. You can apply a patch via composer save as in drupal.org, it's just a reference to an attachment. Releases are done in drupal.org.
Also please avoid being rude and using caps in your requests.
Thanks

**Comment by ghost** [comment]
Hi @jayelless, that's is something that you can only request to the module maintainers, the issue queue is not enabled for the module so I did the best I could.

I agree with you so maybe we can create an issue here to request that.

**Comment by jayelless** [comment]
I apologise for offending people, but I get frustrated with module maintainers who don't use the drupal.org infrastructure.  They are making use of their module more difficult than it needs to be.  The drupal.org infrastructure provides great tools, and is considerably easier to use than other options like github.  I do not contribute reports or patches to drupal module projects on github as the process is foreign to me.

**Comment by duartegarin** [comment]
Hi @jayelless ,

I understand that, but you are merely looking at it from a "consumer" perspective.

For maintainers that might not necessarily be the case.

My entire workflow is based on Github so it makes it extremely easier for me to use and handle issues. Also:

- I personally don't understand us still submitting changes via patches in 2021. Patches are archaic and have no place in modern workflows (imo). We use pull requests which are much easier to manage.
- You _can_  still use patches if you want to (composer only needs a url for the patch)

Although I do understand your point, remember this is just code I wrote that I thought would benefit the community. Feel free to change, fork, do whatever you want with it, but for now, with the limited time I have available I prefer to have a consolidate workflow for all my projects, for better or worse.

Still, as @jidrone-mbm suggests, definitely open an issue for this, it's not out of the question for me at all. Maybe there is a way for us to get the best of both worlds.

Hope that explains things!

**Comment by carolpettirossi** [comment]
Hi @jidrone-mbm, 

Thanks for the patch. I've just pushed to 2.x branch and it will be available in the next release. 

Cheers,
Carol
